const ANCESTRAL_SPIRITS = ["0 filler", "Friendly, POW 5D6+6, 4D3 Spirit Spells, 3D6 Rune Points",
"Friendly, POW 4D6+6, 3D3 Spirit Spells, 2D6 Rune Points",
'"',
'"',
"Friendly, POW 3D6+6, 2D3 Spirit Spells, 1D6 Rune Points",
'"',
'"',
'"',
'"',
"Friendly, POW 2D6+6, 1D3 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
"Friendly, POW 1D6+6, 1 Spirit Spell, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
"Neutral, POW 5D6+6, 3D3 Spirit Spells, 2D6 Rune Points",
'"',
'"',
"Neutral, POW 4D6+6, 2D3 Spirit Spells, 1D6 Rune Points",
'"',
'"',
'"',
'"',
'"',
"Neutral, POW 3D6+6, 1D3 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
"Neutral, POW 2D6+6, 1 Spirit Spell, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
"Neutral, POW 1D6+6, 0 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
"Malign, POW 1D6+6, 0 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
'"',
"Malign, POW 2D6+6, 0 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
'"',
'"',
"Malign, POW 3D6+6, 1D3 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
'"',
'"',
"Malign, POW 4D6+6, 2D3 Spirit Spells, 0 Rune Points",
'"',
'"',
'"',
"Malign, POW 5D6+6, 3D3 Spirit Spells, 1D6 Rune Points",
'"'];


function doHandle(userCommand, args, utils, command) {
  let r = utils.handler100s(userCommand, args, utils, command);
  if (r)
    r += "\nUse /rq ss ... to generate random spirit spells";

  return r;
}


module.exports = {
  name: "Ancestral Spirit",
  aliases: ['sp', 'spirit', 'summon', 'ancestralspirit'],
  data: ANCESTRAL_SPIRITS,
  doHandle,
  help: "Summon an ancestral spirit"
}
