const ChaosFeatures = [ "0 filler", "+1D6 POW",
 "+1D6 POW",
 "+1D6 POW",
 "+2D6 POW",
 "+2D6 POW",
 "+3D6 POW",
 "+2D6 DEX",
 "+2D6 DEX",
 "+4D6 DEX",
 "+2D6 STR",
 "+2D6 STR",
 "+4D6 STR",
 "+2D6 CON",
 "+2D6 CON",
 "+4D6 CON",
 "+2D6 SIZ",
 "+2D6 SIZ",
 "+4D6 SIZ",
 "Spits acid of 2D10 POT 1D6 times per day with six-meter range.",
 "Spits acid of 2D10 POT 1D6 times per day with six-meter range.",
 "Breathes 3D10 fire 1D6 times per day; single target, three-meter range.",
 "Breathes 3D10 fire 1D6 times per day; single target, three-meter range.",
 "Highly flammable; if ignited, bums all within a three-meter radius.",
 "Extra sensory organs.",
 "Extra sensory organs.",
 "Extra sensory organs.",
 "Appearance confusing—subtract –20% from all attacks directed at it.",
 "Appearance confusing—subtract –20% from all attacks directed at it.",
 "Appearance confusing—subtract –30% from all attacks directed at it.",
 "Appearance confusing—subtract –40% from all attacks directed at it.",
 "Poison touch, 2D10 POT; must penetrate armor to work.",
 "Poison touch, 2D10 POT; must penetrate armor to work.",
 "+6-point skin (treat as armor)",
 "+6-point skin (treat as armor)",
 "+6-point skin (treat as armor)",
 "+9-point skin (treat as armor)",
 "+9-point skin (treat as armor)",
 "+12-point skin (treat as armor)",
 "+12-point skin (treat as armor)",
 "Absorbs spells up to 2 magic points, adding magic points absorbed to self.",
 "Absorbs spells up to 2 magic points, adding magic points absorbed to self.",
 "Absorbs spells up to 2 magic points, adding magic points absorbed to self.",
 "Absorbs spells up to 4 magic points, adding magic points absorbed to self.",
 "Absorbs spells up to 4 magic points, adding magic points absorbed to self.",
 "Absorbs spells up to 2D6 magic points, adding magic points absorbed to self.",
 "Reflects spells up to 2 magic points back at caster, without harm to itself.",
 "Reflects spells up to 2 magic points back at caster, without harm to itself.",
 "Reflects spells up to 2 magic points back at caster, without harm to itself.",
 "Reflects spells up to 4 magic points back at caster, without harm to itself.",
 "Reflects spells up to 4 magic points back at caster, without harm to itself.",
 "Reflects spells up to 2D6 magic points back at caster without harm to itself.",
 "Its spirit attacks the adventurer that killed it in spirit combat after it is dead. If it possesses its killer, it will take them over.",
 "Its spirit attacks the adventurer that killed it in spirit combat after it is dead. If it possesses its killer, it will take them over.",
 "Its spirit attacks the adventurer that killed it in spirit combat after it is dead. If it possesses its killer, it will take them over.",
 "+2D6 meters MOV per strike rank.",
 "+2D6 meters MOV per strike rank.",
 "Explodes upon death, doing 1–6D6 (roll 1D6 to determine how many D6s to roll) damage to all within three meters.  Armor helps against this damage.",
 "Explodes upon death, doing 1–6D6 (roll 1D6 to determine how many D6s to roll) damage to all within three meters.  Armor helps against this damage.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Regenerates 2D6–5 hit points per round (minimum of 1 point) in each injured hit location until dead.",
 "Utters agonizing screams when moving.",
 "Utters agonizing screams when moving.",
 "Valuable gem or metal (worth 1D10×100 L) visible on body; this could also be a valuable hide, metal teeth, etc.",
 "Valuable gem or metal (worth 1D10×100 L) visible on body; this could also be a valuable hide, metal teeth, etc.",
 "Valuable gem or metal (worth 1D6×1,000 L) hidden within body; could also be internal organ of some precious metal or an enchanted item of some sort.",
 "Overpowering stench; those nearby must make CON×5 or less on D100 or lose consciousness.",
 "Overpowering stench; those nearby must make CON×5 or less on D100 or lose consciousness.",
 "Hideous; those seeing it make POW×5 or less on 1D100 or be demoralized (per the Demoralize spell, page 112).",
 "Hideous; those seeing it make POW×5 or less on 1D100 or be demoralized (per the Demoralize spell, page 112).",
 "Automatically Befuddles one opponent per round (per the Befuddle spell, page 110) in addition to other attacks (still must overcome the target’s magic points).",
 "Automatically Befuddles one opponent per round (per the Befuddle spell, page 110) in addition to other attacks (still must overcome the target’s magic points).",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Functional extra appendage or body part. Modify hit locations accordingly.",
 "Double power of creature’s normal Chaos ability (e.g., a gorp could have 16-point acid, or a jack o’bear be able to Harmonize twice per round).",
 "Double power of creature’s normal Chaos ability (e.g., a gorp could have 16-point acid, or a jack o’bear be able to Harmonize twice per round).",
 "TBD",
 "TBD",
 "Capable of leaping up to DEX in meters.",
 "Capable of leaping up to DEX in meters.",
 "Hypnotic appearance; roll INT×5 or less on D100 or stand spellbound until it eats the target or leaves its presence.",
 "Hypnotic appearance; roll INT×5 or less on D100 or stand spellbound until it eats the target or leaves its presence.",
 "Appears to be a harmless creature or object until engaged in melee.",
 "Roll from the Curse of Thed table (page 26).",
 "Roll from the Curse of Thed table (page 26).",
 "Roll from the Curse of Thed table (page 26).",
 "Roll from the Curse of Thed table (page 26).",
 "Roll from the Curse of Thed table (page 26)"
];

module.exports = {
  name: "ChaosFeature",
  aliases: ['cf', 'chaosfeature'],
  data: ChaosFeatures,
  help: "todo"
}
