const CurseOfThed = ["0 filler", "Lose 1D6 POW",
"Lose 1D6 POW",
"Lose 1D6 POW",
"Lose 2D6 POW",
"Lose 2D6 POW",
"Lose 3D6 POW",
"Lose 1D6 DEX",
"Lose 1D6 DEX",
"Lose 1D6 DEX",
"Lose 2D6 DEX",
"Lose 2D6 DEX",
"Lose 3D6 DEX",
"Lose 2D6 STR",
"Lose 2D6 STR",
"Lose 4D6 STR",
"Lose 2D6 CON",
"Lose 2D6 CON",
"Lose 4D6 CON",
"+3 to victim’s strike rank for duration of spell.",
"+3 to victim’s strike rank for duration of spell.",
"May not resist any 1-point spells cast at the victim.",
"May not resist any 1-point spells cast at the victim.",
"Drenched in acid, 2D10 potency (one round only).",
"Drenched in acid, 2D10 potency (one round only).",
"Engulfed in flame, 3D10 damage (one round only).",
"Engulfed in flame, 3D10 damage (one round only).",
"Attracts magic: all 1-point attack spells cast in a 20-meter radius automatically targets against the victim.",
"Attracts magic: all 1-point attack spells cast in a 20-meter radius automatically targets against the victim.",
"Victim becomes immune to fire damage for duration of spell.",
"Victim becomes immune to fire damage for duration of spell.",
"Roll equal to or below INT×5 on D100 or stand stupefied for 15 minutes.",
"Roll equal to or below INT×5 on D100 or stand stupefied for 15 minutes.",
"All foes have +20% chance to hit victim.*",
"All foes have +20% chance to hit victim.*",
"All foes have +20% chance to hit victim.*",
"One valuable gem, magic item, or weapon in the victim’s possession is eaten by Chaos and disappears forever.",
"One valuable gem, magic item, or weapon in the victim’s possession is eaten by Chaos and disappears forever.",
"Takes 1 point of damage in random location each melee round until spell expires.*",
"Takes 1 point of damage in random location each melee round until spell expires.*",
"Takes 1 point of damage in random location each melee round until spell expires.*",
"Victim befuddled for spell duration.",
"Victim befuddled for spell duration.",
"Non-Rune metals do double damage to victim.",
"Non-Rune metals do double damage to victim.",
"Non-Rune metals do double damage to victim.",
"Victim is rendered incapable of physically attacking.*",
"All foes have +30% chance to hit victim.*",
"All foes have +30% chance to hit victim.*",
"Attacked by poison, 2010 potency (one round only).",
"Attacked by poison, 2010 potency (one round only).",
"Takes 3 points of damage in random location each melee round until spell expires.*",
"Takes 3 points of damage in random location each melee round until spell expires.*",
"Add +3 to damage of all weapons hitting the victim.*",
"Add +3 to damage of all weapons hitting the victim.*",
"Victim bound as in Binding spell (page 110).",
"Victim bound as in Binding spell (page 110).",
"Victim cannot resist 1- or 2-point spells.",
"Victim cannot resist 1- or 2-point spells.",
"A spirit of 3D6 POW engages the victim in spirit combat.",
"A spirit of 3D6 POW engages the victim in spirit combat.",
"Explosion, 3D6 damage to the victim and all within three meters (one round only).",
"Explosion, 3D6 damage to the victim and all within three meters (one round only).",
"Victim becomes physically indistinguishable from caster of spell.",
"Victim becomes physically indistinguishable from caster of spell.",
"Victim becomes physically indistinguishable from caster of spell.",
"Victim becomes silent when moving; adds +25% permanently to Move Silent skill.",
"Victim becomes silent when moving; adds +25% permanently to Move Silent skill.",
"Target becomes magic attractant for 1- and 2-point spells: all spirit magic spells cast at anyone, beneficial or harmful,within three meters of the target instead strike target.",
"Target becomes magic attractant for 1- and 2-point spells: all spirit magic spells cast at anyone, beneficial or harmful,within three meters of the target instead strike target.",
"Target becomes magic attractant for 1- and 2-point spells: all spirit magic spells cast at anyone, beneficial or harmful,within three meters of the target instead strike target.",
"Add +4 points to all weapon damage against the victim.*",
"Add +4 points to all weapon damage against the victim.*",
"Add +5 points to all weapon damage against the victim.*",
"Add +5 points to all weapon damage against the victim.*",
"Add +6 points to all weapon damage against the victim.*",
"Add +6 points to all weapon damage against the victim.*",
"Victim cannot cast offensive magic.*",
"Victim takes 10D6 points of damage in random location each round until spell expires.*",
"Victim takes 10D6 points of damage in random location each round until spell expires.*",
"Victim takes 10D6 points of damage in random location each round until spell expires.*",
"Victim immobilized.",
"Victim immobilized.",
"Victim goes berserk (per the Fanaticism spell, page 114).",
"Victim goes berserk (per the Fanaticism spell, page 114).",
"Foes have +40% chance to hit victim.",
"All objects on victim’s body are devoured by Chaos, and victim stands naked and weaponless.",
"All objects on victim’s body are devoured by Chaos, and victim stands naked and weaponless.",
"Victim can make no vocal sounds, including spell casting.",
"Victim can make no vocal sounds, including spell casting.",
"Victim can make no vocal sounds, including spell casting.",
"Roll CON×5 or lose consciousness for spell duration.",
"Roll CON×5 or lose consciousness for spell duration.",
"Victim becomes magic attractant for all spells, beneficial or harmful, within 3 meters.",
"Victim becomes magic attractant for all spells, beneficial or harmful, within 3 meters.",
"Victim Demoralized for spell duration (per the Demoralize spell, page 112).",
"Victim Demoralized for spell duration (per the Demoralize spell, page 112).",
"Lose 2D6 SIZ.",
"Lose 2D6 SIZ.",
"Roll twice, rolling again if this result is rolled once more.",
"Victim joins caster’s side for duration of spell."
];

module.exports = {
  name: "CurseOfThed",
  aliases: ['ct', 'cot', 'thed', 'curseofthed'],
  data: CurseOfThed,
  help: 'todo'
}
